### ISSUE TITLE
Problem s intalaciou crx

### ISSUE THREAD

**Issue by duffysk** [viliampucik/majster-n#3]
Pri inštalácii do Chrome, 
Zahlási: Attempted to downgrade extnention. Pod kliknutí Ok Majstra N! nenainštaluje.

Verzia Chrome: Version 60.0.3112.113 (Official Build) (64-bit) (OSX Sierra 10.12.6)

![screen shot 2017-10-03 at 09 07 42](https://user-images.githubusercontent.com/8058590/31113603-609382ba-a81a-11e7-8da7-501dd365d4b0.png)

**Comment by viliampucik** [comment]
Prejavuje sa dana chyba aj v najnovsej verzii Chrome 61?

Ak ano, odporucam pockat na oficialne vydanie Majster N! v Chrome Store.

Ako docasne riesenie sa da pouzit [stiahnutie](https://github.com/viliampucik/majster-n/archive/master.zip) samotnych zdrojovych kodov rozsirenia, ich rozbalenie niekam na disk a nasledne nacitanie cez _Load unpacked extension..._.

**Comment by duffysk** [comment]
Ano, rozbalil som crx a nainstaloval unpacked extention, takto to funguje.

**Comment by viliampucik** [comment]
Ospravedlnujem sa za problemy s CRX. Nastastie teraz je mozne rozsirenie nainstalovat aj priamo z Chrome Store: https://chrome.google.com/webstore/detail/majster-n/hblocgkbkaoehofhapgpjmagalooopbd
